#ifndef DEFINES_H
#define DEFINES_H


#define FONT_SIZE_SMALL 40
#define FONT_SIZE_MEDIUM 50
#define FONT_SIZE_BIG 150


#define DELAY_VICTORY 6000
#define DELAY_GAMEOVER 4000


#define SCALE 3
#define PERIOD 20
#define GRAVITY 2


#define SCORE_VY -5
#define SCORE_CLIMBING_TIME 20
#define SCORE_BRICK 50
#define SCORE_KILL 100
#define SCORE_COIN 200
#define SCORE_MUSHROOM_HEALTH 1000
#define SCORE_MUSHROOM_RED 1000
#define SCORE_FLOWER 1000


#define OBJECT_LENGTH (SCALE*16)
#define OBJECT_WIDTH (SCALE*16)
#define OBJECT_JUMP_SPEED -2
#define OBJECT_JUMP_VALUE 16
#define OBJECT_QUESTION_STATUS_NUM 5
#define OBJECT_QUESTION_STATUS_MAX 15


#define PRIZE_LENGTH (SCALE*16)
#define PRIZE_WIDTH (SCALE*16)
#define PRIZE_VX 3
#define PRIZE_VY -4
#define COIN_VY -15
#define PRIZE_CLIMBING_TIME (OBJECT_WIDTH/(-PRIZE_VY))


#define ENEMY_LENGTH (SCALE*16)
#define GOOMBA_WIDTH (SCALE*16)
#define KOOPA_WIDTH (SCALE*25)
#define ENEMY_VX 3
#define KOOPA_ZOMBIE_VX 16
#define ENEMY_DEATH_TIME 30
#define ENEMY_WALKING_STATUS_NUM 5
#define ENEMY_WALKING_STATUS_MAX 10


#define MARIO_LENGTH (SCALE*16)
#define MARIO_WIDTH_NORMAL (SCALE*16)
#define MARIO_WIDTH_BIG_WHITE (SCALE*32)
#define MARIO_VX 8
#define MARIO_VY -30
#define MARIO_LIVES 3
#define MARIO_DEATH_TIME 200
#define MARIO_GHOST_TIME 175
#define MARIO_WALKING_STATUS_NUM 3
#define MARIO_WALKING_STATUS_MAX 9
#define MARIO_SLIDING_STATUS_PERIOD 3
#define MARIO_GHOST_BLINKING_PERIOD 8
#define MARIO_FIRE_DELAY 30


#define FIREBALL_LENGTH (SCALE*6)
#define FIREBALL_WIDTH (SCALE*6)
#define FIREBALL_VX 12
#define FIREBALL_VY -13


#define BACKGROUND_LENGTH 2000
#define BACKGROUND_WIDTH 1000
#define WINDOW_LENGTH (25*OBJECT_LENGTH)


#endif
